"""Self-contained, interactive static HTML replay renderer."""

from __future__ import annotations

import json
import webbrowser
from pathlib import Path
from typing import Any


_TEMPLATE = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#080b19">
<title>Receipts · forensic replay</title>
<style>
:root{color-scheme:dark;--ink:#f8f9ff;--soft:#c3cbe3;--muted:#8792b2;--cyan:#75e4ff;--violet:#ae91ff;--mint:#72efc0;--amber:#ffd36b;--red:#ff7d9b;--night:#080b19;--glass:rgba(18,27,56,.66);--hair:rgba(219,231,255,.17);--hairhot:rgba(200,222,255,.34);--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;--shadow:0 26px 80px rgba(0,0,0,.34),inset 0 1px 0 rgba(255,255,255,.09)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{min-width:320px;margin:0;background:radial-gradient(circle at 7% 4%,rgba(129,89,255,.25),transparent 27rem),radial-gradient(circle at 93% 16%,rgba(74,214,255,.19),transparent 29rem),#080b19;color:var(--ink);font:15px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}body:before{position:fixed;inset:0;z-index:-1;background-image:linear-gradient(rgba(164,185,240,.03) 1px,transparent 1px),linear-gradient(90deg,rgba(164,185,240,.03) 1px,transparent 1px);background-size:44px 44px;content:"";mask-image:linear-gradient(to bottom,black,transparent 78%)}button,input{font:inherit}button{cursor:pointer}code{font-family:var(--mono)}a{color:inherit}.shell{width:min(1440px,calc(100% - 2.5rem));margin:auto}.skip{position:absolute;top:-4rem;left:1rem;z-index:99;padding:.7rem 1rem;border-radius:.6rem;background:white;color:#0c1325;font-weight:800}.skip:focus{top:1rem}
.top{position:sticky;top:0;z-index:20;padding:13px 0;background:linear-gradient(to bottom,rgba(8,11,25,.82),rgba(8,11,25,.26));backdrop-filter:blur(12px)}.nav{display:flex;align-items:center;gap:1rem;min-height:58px;padding:.55rem .7rem .55rem 1rem;border:1px solid var(--hair);border-radius:1.05rem;background:linear-gradient(120deg,rgba(31,44,84,.74),rgba(11,17,37,.59));box-shadow:var(--shadow);backdrop-filter:blur(22px) saturate(145%)}.brand{display:inline-flex;align-items:center;gap:.62rem;font-size:1.02rem;font-weight:850;letter-spacing:-.04em}.brand-mark{width:30px;height:30px;display:grid;place-items:center;border:1px solid rgba(117,228,255,.48);border-radius:.68rem;background:linear-gradient(135deg,rgba(117,228,255,.22),rgba(174,145,255,.13));color:var(--cyan)}.brand-mark svg{width:18px;height:18px}.crumb{color:var(--muted);font:700 .7rem var(--mono)}.nav-space{margin-left:auto}.pill{display:inline-flex;align-items:center;gap:.4rem;padding:.34rem .55rem;border:1px solid rgba(114,239,192,.34);border-radius:999px;background:rgba(114,239,192,.08);color:#c4fae0;font-size:.63rem;font-weight:810;letter-spacing:.06em;text-transform:uppercase;white-space:nowrap}.pill:before{width:.38rem;height:.38rem;border-radius:50%;background:var(--mint);box-shadow:0 0 11px rgba(114,239,192,.65);content:""}.back{color:var(--soft);font-size:.75rem;font-weight:750;text-decoration:none}.back:hover{color:white}
.app{padding:2.35rem 0 3rem}.hero{display:flex;justify-content:space-between;gap:2rem;align-items:end;margin-bottom:1.3rem}.eyebrow{margin:0 0 .72rem;color:var(--cyan);font-size:.68rem;font-weight:850;letter-spacing:.13em;text-transform:uppercase}.hero h1{margin:0;font-size:clamp(2rem,3.6vw,3.5rem);line-height:1.02;letter-spacing:-.065em}.hero h1 span{color:#d7c6ff}.hero p{max-width:640px;margin:.8rem 0 0;color:var(--soft);font-size:.91rem}.hero-actions{display:flex;flex-wrap:wrap;gap:.65rem}.action{display:inline-flex;align-items:center;justify-content:center;gap:.48rem;min-height:40px;padding:.55rem .78rem;border:1px solid var(--hairhot);border-radius:.7rem;background:rgba(255,255,255,.045);color:#eaf0ff;font-size:.75rem;font-weight:800;transition:transform .16s ease,background .16s ease,border-color .16s ease}.action:hover,.action:focus-visible{transform:translateY(-2px);background:rgba(117,228,255,.11);border-color:rgba(117,228,255,.62)}.action.primary{border-color:transparent;background:linear-gradient(120deg,#7be7ff,#b6a0ff);color:#091022;box-shadow:0 10px 24px rgba(103,192,255,.2)}.action svg{width:15px;height:15px}
.summary{display:grid;grid-template-columns:1.18fr repeat(4,minmax(110px,.35fr));gap:1px;overflow:hidden;margin-bottom:1.3rem;border:1px solid var(--hair);border-radius:1rem;background:var(--hair);box-shadow:var(--shadow)}.summary>*{min-height:104px;padding:1.15rem;background:rgba(18,28,58,.68);backdrop-filter:blur(19px)}.session-head{position:relative;overflow:hidden}.session-head:after{position:absolute;right:-30px;bottom:-40px;width:170px;height:170px;border-radius:50%;background:radial-gradient(circle,rgba(117,228,255,.17),transparent 70%);content:""}.session-head p{margin:.45rem 0 0;color:var(--soft);font-size:.78rem}.session-head code{color:#e6edff}.stat{border-left:1px solid var(--hair)}.stat b{display:block;font-size:1.55rem;line-height:1;letter-spacing:-.05em}.stat:last-child b{color:var(--red)}.stat span{display:block;overflow:hidden;margin-top:.35rem;color:var(--muted);font-size:.6rem;font-weight:800;letter-spacing:.055em;text-overflow:ellipsis;text-transform:uppercase;white-space:nowrap}.integrity{display:flex;align-items:center;gap:.52rem;margin-top:.5rem;color:var(--muted);font:600 .68rem var(--mono)}.integrity i{width:7px;height:7px;border-radius:50%;background:var(--violet);box-shadow:0 0 0 4px rgba(174,145,255,.1)}.integrity.good{color:#c8fbe2}.integrity.good i{background:var(--mint);box-shadow:0 0 0 4px rgba(114,239,192,.12)}.integrity.bad{color:#ffd4dc}.integrity.bad i{background:var(--red);box-shadow:0 0 0 4px rgba(255,125,155,.13)}
.workspace{display:grid;grid-template-columns:220px minmax(0,1fr) minmax(290px,.62fr);gap:1rem;align-items:start}.glass{border:1px solid var(--hair);border-radius:1rem;background:linear-gradient(135deg,rgba(25,38,75,.7),rgba(11,17,38,.65));box-shadow:var(--shadow);backdrop-filter:blur(22px) saturate(145%)}.filters{padding:.9rem}.filters h2,.inspector h2{margin:0;color:var(--soft);font-size:.67rem;letter-spacing:.1em;text-transform:uppercase}.filter-list{display:grid;gap:.36rem;margin-top:.8rem}.filter{display:flex;align-items:center;justify-content:space-between;gap:.5rem;width:100%;padding:.64rem .65rem;border:1px solid transparent;border-radius:.65rem;background:transparent;color:var(--soft);font-size:.76rem;font-weight:720;text-align:left}.filter:hover,.filter:focus-visible{background:rgba(255,255,255,.05);color:white}.filter.active{border-color:rgba(117,228,255,.32);background:rgba(117,228,255,.11);color:#dff8ff}.filter b{min-width:22px;padding:.12rem .35rem;border:1px solid var(--hair);border-radius:999px;color:var(--muted);font:700 .62rem var(--mono);text-align:center}.filter.active b{color:var(--cyan)}.filters hr{border:0;border-top:1px solid var(--hair);margin:1rem 0}.filters p{margin:0;color:var(--muted);font-size:.7rem;line-height:1.55}.file-load{display:none}.drop-button{width:100%;margin-top:.75rem}.privacy-note{margin-top:.8rem!important;padding:.7rem;border-left:2px solid var(--violet);border-radius:0 .5rem .5rem 0;background:rgba(174,145,255,.08);color:#d8ceff!important}
.timeline-panel{overflow:hidden}.timeline-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1rem 1rem .85rem;border-bottom:1px solid var(--hair)}.timeline-head h2{margin:0;font-size:.95rem;letter-spacing:-.025em}.timeline-head span{color:var(--muted);font:600 .66rem var(--mono)}.scrubber{display:grid;grid-template-columns:auto 1fr auto;gap:.65rem;align-items:center;padding:.85rem 1rem;border-bottom:1px solid var(--hair);background:rgba(7,12,27,.18)}.scrubber output{min-width:42px;color:#dce8ff;font:700 .67rem var(--mono);text-align:right}.play{width:30px;height:30px;display:grid;place-items:center;padding:0;border:1px solid rgba(117,228,255,.36);border-radius:.55rem;background:rgba(117,228,255,.09);color:var(--cyan);font-size:.76rem}.range{width:100%;accent-color:var(--cyan)}.events{display:grid;gap:.55rem;max-height:605px;min-height:400px;overflow:auto;padding:1rem}.event{display:grid;grid-template-columns:50px 11px minmax(0,1fr) auto;align-items:center;gap:.65rem;width:100%;padding:.72rem;border:1px solid rgba(255,255,255,.055);border-radius:.72rem;background:rgba(255,255,255,.03);color:inherit;text-align:left;transition:transform .15s ease,border-color .15s ease,background .15s ease}.event:hover,.event:focus-visible,.event.selected{transform:translateY(-1px);border-color:rgba(117,228,255,.42);background:rgba(117,228,255,.09)}.event.alert{border-color:rgba(255,125,155,.35);background:rgba(255,125,155,.075)}.event time{color:var(--muted);font:650 .64rem var(--mono)}.dot{width:10px;height:10px;border-radius:50%;background:var(--violet);box-shadow:0 0 0 4px rgba(174,145,255,.11)}.event.test .dot{background:var(--mint);box-shadow:0 0 0 4px rgba(114,239,192,.12)}.event.flag .dot,.event.alert .dot{background:var(--red);box-shadow:0 0 0 4px rgba(255,125,155,.14)}.event b{display:block;overflow:hidden;color:#eef3ff;font:700 .72rem var(--mono);text-overflow:ellipsis;white-space:nowrap}.event small{display:block;overflow:hidden;margin-top:.16rem;color:var(--muted);font-size:.66rem;text-overflow:ellipsis;white-space:nowrap}.event-tag{padding:.2rem .38rem;border:1px solid var(--hair);border-radius:999px;color:var(--muted);font-size:.57rem;font-weight:800;letter-spacing:.05em;text-transform:uppercase;white-space:nowrap}.empty{padding:2rem 1rem;color:var(--muted);font-size:.82rem;text-align:center}
.inspector{position:sticky;top:84px;padding:1rem}.inspector h2{margin-bottom:.9rem}.inspector-title{margin:0;color:white;font:800 .84rem var(--mono);word-break:break-word}.inspector-subtitle{margin:.4rem 0 .85rem;color:var(--soft);font-size:.73rem}.chips{display:flex;flex-wrap:wrap;gap:.38rem;margin-bottom:1rem}.chip{padding:.25rem .42rem;border:1px solid var(--hair);border-radius:999px;color:var(--soft);font-size:.61rem;font-weight:780}.chip.red{border-color:rgba(255,125,155,.4);background:rgba(255,125,155,.1);color:#ffc0cd}.chip.green{border-color:rgba(114,239,192,.35);background:rgba(114,239,192,.08);color:#c3fbe0}.chip.amber{border-color:rgba(255,211,107,.35);background:rgba(255,211,107,.08);color:#ffe69f}.facts{display:grid;gap:.5rem;margin:0;padding:0;list-style:none}.fact{display:grid;grid-template-columns:1fr auto;gap:.7rem;padding:.58rem 0;border-top:1px solid var(--hair);color:var(--muted);font-size:.68rem}.fact code,.fact b{max-width:145px;overflow:hidden;color:#e9efff;font:700 .66rem var(--mono);text-align:right;text-overflow:ellipsis;white-space:nowrap}.fact b.red{color:#ffb7c7}.inspector-actions{display:grid;grid-template-columns:1fr 1fr;gap:.55rem;margin-top:1rem}.inspector-actions .action{padding:.48rem;font-size:.67rem}.raw{margin-top:1rem;padding-top:1rem;border-top:1px solid var(--hair)}.raw summary{color:var(--soft);font-size:.72rem;font-weight:750;cursor:pointer}.raw pre{max-height:190px;margin:.7rem 0 0;overflow:auto;padding:.7rem;border:1px solid var(--hair);border-radius:.55rem;background:rgba(5,9,20,.4);color:#cbd6ee;font:600 .61rem/1.5 var(--mono);white-space:pre-wrap;word-break:break-word}
.footer{padding:1.4rem 0 2rem;color:var(--muted);font-size:.7rem;text-align:center}.footer b{color:var(--soft)}:focus-visible{outline:3px solid rgba(117,228,255,.7);outline-offset:3px}@media(max-width:1120px){.workspace{grid-template-columns:190px minmax(0,1fr)}.inspector{position:static;grid-column:1/-1}.summary{grid-template-columns:1fr repeat(4,minmax(100px,.35fr))}}@media(max-width:760px){.shell{width:min(100% - 1.35rem,1440px)}.crumb,.back{display:none}.hero{display:block}.hero-actions{margin-top:1rem}.summary{grid-template-columns:repeat(2,1fr)}.session-head{grid-column:1/-1}.stat:nth-child(2n+1){border-left:0}.workspace{grid-template-columns:1fr}.filters{display:grid;grid-template-columns:1fr auto;gap:1rem}.filters .filter-list{grid-column:1/-1;grid-template-columns:repeat(2,1fr)}.filters hr{display:none}.filters .drop-button{grid-column:2;grid-row:1;margin:0}.filters .privacy-note{display:none}.events{min-height:310px}.event{grid-template-columns:44px 10px minmax(0,1fr)}.event-tag{display:none}.inspector{grid-column:auto}.nav-space{display:none}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*:before,*:after{transition-duration:.01ms!important;animation-duration:.01ms!important}}
</style>
</head>
<body>
<a class="skip" href="#evidence">Skip to evidence</a>
<header class="top"><div class="shell nav"><div class="brand"><span class="brand-mark"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M7 3h10a2 2 0 0 1 2 2v16l-3-2-4 2-4-2-3 2V5a2 2 0 0 1 2-2Z" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/><path d="M9 8h6M9 12h6M9 16h3" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg></span>Receipts</div><span class="crumb">/ forensic replay</span><span class="nav-space"></span><span class="pill">offline artifact</span><a class="back" href="index.html">← demo home</a></div></header>
<main class="shell app" id="evidence">
  <section class="hero"><div><p class="eyebrow">Session intelligence / locally inspectable</p><h1 id="title">Forensic <span>replay</span></h1><p id="subtitle">Loading embedded receipt…</p></div><div class="hero-actions"><button class="action primary" id="focus-red" type="button">Focus red flag</button><button class="action" id="verify-receipt" type="button">Verify in browser</button></div></section>
  <section class="summary" aria-label="Session summary"><div class="session-head"><p class="eyebrow">Recorded evidence</p><strong id="task">Loading task…</strong><p><code id="session-id">embedded manifest</code></p><div class="integrity" id="integrity"><i></i><span>sha256 ready to verify · unsigned</span></div></div><div class="stat"><b id="stat-duration">–</b><span>session duration</span></div><div class="stat"><b id="stat-files">–</b><span>changed paths</span></div><div class="stat"><b id="stat-tests">–</b><span>test runs</span></div><div class="stat"><b id="stat-gaps">–</b><span>never executed</span></div></section>
  <section class="workspace">
    <aside class="filters glass"><div><h2>Evidence filters</h2><div class="filter-list" id="filter-list"><button class="filter active" type="button" data-filter="all">All evidence <b id="count-all">0</b></button><button class="filter" type="button" data-filter="changes">Changes <b id="count-changes">0</b></button><button class="filter" type="button" data-filter="tests">Tests <b id="count-tests">0</b></button><button class="filter" type="button" data-filter="flags">Flags <b id="count-flags">0</b></button><button class="filter" type="button" data-filter="red">After last test <b id="count-red">0</b></button></div></div><hr><input class="file-load" id="manifest-file" type="file" accept="application/json,.json"><button class="action drop-button" id="load-receipt" type="button">Load another receipt</button><p class="privacy-note">Local-only: selecting a JSON receipt renders it in this browser. It is never uploaded.</p></aside>
    <section class="timeline-panel glass"><div class="timeline-head"><h2>Observed event timeline</h2><span id="timeline-state">0 events visible</span></div><div class="scrubber"><button class="play" id="play" type="button" aria-label="Play timeline">▶</button><input class="range" id="scrubber" type="range" min="0" max="1" value="1" step="0.1" aria-label="Timeline position"><output id="scrubber-output">00:00.0</output></div><div class="events" id="events" aria-live="polite"></div></section>
    <aside class="inspector glass" id="inspector"><h2>Evidence inspector</h2><p class="inspector-title" id="inspector-title">Select an event</p><p class="inspector-subtitle" id="inspector-subtitle">The selected event’s observed evidence appears here.</p><div class="chips" id="chips"></div><ul class="facts" id="facts"></ul><div class="inspector-actions"><button class="action" id="copy-link" type="button">Copy share link</button><button class="action" id="download-receipt" type="button">Download manifest</button></div><details class="raw"><summary>Show raw embedded manifest</summary><pre id="raw"></pre></details></aside>
  </section>
</main>
<footer class="footer"><b>Static delivery. Interactive evidence.</b> This viewer contains its manifest, filters evidence locally, and can independently recompute the SHA-256 receipt.</footer>
<script id="manifest" type="application/json">__MANIFEST_JSON__</script>
<script>
(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const q = (selector) => document.querySelectorAll(selector);
  const initialManifest = JSON.parse($("manifest").textContent);
  let active = initialManifest, allEvents = [], selectedId = "", filter = "all", position = 0, player = null;
  const label = (status) => ({verified:"verified",indirectly_exercised:"indirectly exercised",never_executed:"NEVER EXECUTED"}[status] || status || "unparsed");
  const short = (value="") => value ? `${value.slice(0,4)}…${value.slice(-4)}` : "unavailable";
  const timeMs = (timestamp) => { const value = Date.parse(timestamp); return Number.isNaN(value) ? null : value; };
  const startMs = () => timeMs(active.meta?.started_at) || 0;
  const duration = () => Number(active.meta?.duration_seconds || 0);
  const seconds = (timestamp) => { const value = timeMs(timestamp); return value === null ? null : Math.max(0,(value-startMs())/1000); };
  const clock = (value) => `00:${Number(value || 0).toFixed(1).padStart(4,"0")}`;
  const canonicalize = (value) => Array.isArray(value) ? value.map(canonicalize) : value && typeof value === "object" ? Object.keys(value).sort().reduce((out,key)=>{out[key]=canonicalize(value[key]);return out;},{}) : value;
  const canonicalBody = (manifest) => { const body={...manifest}; delete body.integrity; return JSON.stringify(canonicalize(body)); };
  const hashInBrowser = async (manifest) => { if(!globalThis.crypto?.subtle) throw new Error("Web Crypto is unavailable"); const bytes=new TextEncoder().encode(canonicalBody(manifest)); const digest=await crypto.subtle.digest("SHA-256",bytes); return Array.from(new Uint8Array(digest),byte=>byte.toString(16).padStart(2,"0")).join(""); };
  const create = (tag,className,content) => { const node=document.createElement(tag); if(className)node.className=className; if(content!==undefined)node.textContent=content; return node; };

  function buildEvents() {
    const changes=(active.timeline?.file_changes||[]).map((change,index)=>({id:`change:${index}`,kind:"change",timestamp:change.last_modified_observed_at,path:change.path,detail:"file change observed",raw:change}));
    const tests=(active.timeline?.test_executions||[]).map((run,index)=>({id:`test:${index}`,kind:"test",timestamp:run.timestamp,path:run.command,detail:run.summary||run.result||"test result unparsed",raw:run}));
    const risk=[...(active.analysis?.scope_drift||[]).map((flag,index)=>({id:`scope:${index}`,kind:"flag",timestamp:(changes.find(event=>event.path===flag.path)||{}).timestamp,path:flag.path,detail:`scope drift (heuristic): ${flag.reason}`,raw:flag,red:true})),...(active.analysis?.risk_hints||[]).map((flag,index)=>({id:`risk:${index}`,kind:"flag",timestamp:(changes.find(event=>event.path===flag.path)||{}).timestamp,path:flag.path,detail:flag.reason,raw:flag,red:false}))];
    return {core:[...changes,...tests].sort((a,b)=>(timeMs(a.timestamp)||Infinity)-(timeMs(b.timestamp)||Infinity)),flags:risk.sort((a,b)=>(timeMs(a.timestamp)||Infinity)-(timeMs(b.timestamp)||Infinity))};
  }

  function verificationFor(path) { return (active.analysis?.verification||[]).find(item=>item.path===path); }
  function flagsFor(path) { return [...(active.analysis?.scope_drift||[]),...(active.analysis?.risk_hints||[])].filter(item=>item.path===path); }
  function activeEvents() {
    const cutoff=duration()*position;
    const timed=(event)=>{const value=seconds(event.timestamp); return value===null || value<=cutoff+.001;};
    if(filter==="flags") return allEvents.flags.filter(timed);
    if(filter==="changes") return allEvents.core.filter(event=>event.kind==="change"&&timed(event));
    if(filter==="tests") return allEvents.core.filter(event=>event.kind==="test"&&timed(event));
    if(filter==="red") return allEvents.core.filter(event=>event.kind==="change"&&verificationFor(event.path)?.status==="never_executed"&&timed(event));
    return allEvents.core.filter(timed);
  }

  function setInspector(event) {
    if(!event) return;
    selectedId=event.id;
    const verification=verificationFor(event.path), flags=flagsFor(event.path), timing=seconds(event.timestamp);
    $("inspector-title").textContent=event.path;
    $("inspector-subtitle").textContent=event.kind==="test" ? "Recorded test execution" : event.kind==="flag" ? "Recorded review flag" : "Observed file change";
    const chips=$("chips"); chips.replaceChildren();
    const addChip=(text,kind="")=>chips.append(create("span",`chip ${kind}`,text));
    addChip(event.kind); if(verification)addChip(label(verification.status),verification.status==="never_executed"?"red":verification.status==="verified"?"green":"amber"); for(const flag of flags)addChip(flag.reason.includes("heuristic")?"scope heuristic":"sensitive path",flag.reason.includes("heuristic")?"red":"amber");
    const facts=$("facts"); facts.replaceChildren();
    const addFact=(name,value,kind="")=>{const row=create("li","fact");row.append(create("span","",name),create("b",kind,value));facts.append(row)};
    addFact("observed at",timing===null?"unparsed":clock(timing));
    if(event.kind==="change") { addFact("diff snapshot",short(event.raw.last_diff_sha256)); addFact("verification",verification?label(verification.status):"not classified",verification?.status==="never_executed"?"red":""); const lastTest=[...(active.timeline?.test_executions||[])].filter(run=>run.result==="passed").sort((a,b)=>(timeMs(a.timestamp)||0)-(timeMs(b.timestamp)||0)).at(-1); const testsAfter=(active.timeline?.test_executions||[]).filter(run=>timeMs(run.timestamp)>(timeMs(event.timestamp)||Infinity)); addFact("tests after edit",String(testsAfter.length),verification?.status==="never_executed"?"red":""); if(lastTest&&verification?.status==="never_executed") addFact("after final pass",`${Math.max(0,seconds(event.timestamp)-seconds(lastTest.timestamp)).toFixed(1)}s`,`red`); }
    if(event.kind==="test") { addFact("result",event.raw.result||"unparsed",event.raw.result==="passed"?"":"red"); addFact("summary",event.raw.summary||"unparsed"); }
    if(event.kind==="flag") addFact("reason",event.detail);
    renderEvents();
  }

  function renderEvents() {
    const holder=$("events"), visible=activeEvents(); holder.replaceChildren();
    $("timeline-state").textContent=`${visible.length} evidence item${visible.length===1?"":"s"} visible`;
    if(!visible.length) { holder.append(create("p","empty","No observed evidence matches this filter and timeline position.")); return; }
    for(const event of visible) { const button=create("button",`event ${event.kind}${event.red||verificationFor(event.path)?.status==="never_executed"?" alert":""}${event.id===selectedId?" selected":""}`); button.type="button"; const timestamp=seconds(event.timestamp); button.append(create("time","",timestamp===null?"unparsed":clock(timestamp)),create("span","dot")); const body=create("span",""); body.append(create("b","",event.path),create("small","",event.detail)); button.append(body,create("span","event-tag",event.kind)); button.addEventListener("click",()=>setInspector(event)); holder.append(button); }
  }

  function renderSummary() {
    const verification=active.analysis?.verification||[];
    $("task").textContent=active.meta?.task||"task not recorded"; $("session-id").textContent=`${active.meta?.session_id||"session"} · ${active.meta?.git_branch||"no branch"}`; $("title").innerHTML=`Forensic <span>replay</span>`; $("subtitle").textContent=`${active.meta?.agent||"other"} agent · ${Number(active.meta?.duration_seconds||0).toFixed(1)} seconds recorded · ${(active.timeline?.command_count||0)} terminal commands`;
    $("stat-duration").textContent=`${Number(active.meta?.duration_seconds||0).toFixed(1)}s`; $("stat-files").textContent=String((active.final?.changed_files||[]).length); $("stat-tests").textContent=String((active.timeline?.test_executions||[]).length); $("stat-gaps").textContent=String(verification.filter(item=>item.status==="never_executed").length);
    $("raw").textContent=JSON.stringify(active,null,2); $("scrubber").max=String(Math.max(duration(),.1)); $("scrubber").value=String(duration()); position=1; $("scrubber-output").textContent=clock(duration());
    $("count-all").textContent=String(allEvents.core.length); $("count-changes").textContent=String(allEvents.core.filter(event=>event.kind==="change").length); $("count-tests").textContent=String(allEvents.core.filter(event=>event.kind==="test").length); $("count-flags").textContent=String(allEvents.flags.length); $("count-red").textContent=String(allEvents.core.filter(event=>event.kind==="change"&&verificationFor(event.path)?.status==="never_executed").length);
    const defaultEvent=allEvents.core.find(event=>event.kind==="change"&&verificationFor(event.path)?.status==="never_executed")||allEvents.core[0]; setInspector(defaultEvent);
  }

  function mount(manifest) { active=manifest; allEvents=buildEvents(); filter="all"; selectedId=""; renderSummary(); }
  q(".filter").forEach(button=>button.addEventListener("click",()=>{filter=button.dataset.filter;q(".filter").forEach(item=>item.classList.toggle("active",item===button));renderEvents();}));
  $("scrubber").addEventListener("input",event=>{position=Number(event.target.value)/Math.max(duration(),.1); $("scrubber-output").textContent=clock(Number(event.target.value)); renderEvents();});
  $("play").addEventListener("click",()=>{if(player){clearInterval(player);player=null;$("play").textContent="▶";return;}$("play").textContent="Ⅱ";if(position>=1)position=0;player=setInterval(()=>{position=Math.min(1,position+.025);$("scrubber").value=String(duration()*position);$("scrubber-output").textContent=clock(duration()*position);renderEvents();if(position>=1){clearInterval(player);player=null;$("play").textContent="▶";}},80);});
  $("focus-red").addEventListener("click",()=>{filter="red";q(".filter").forEach(item=>item.classList.toggle("active",item.dataset.filter==="red"));position=1;$("scrubber").value=String(duration());$("scrubber-output").textContent=clock(duration());renderEvents();document.getElementById("events").scrollIntoView({behavior:"smooth",block:"center"});});
  $("verify-receipt").addEventListener("click",async()=>{const button=$("verify-receipt"),state=$("integrity"),expected=active.integrity?.sha256||"";button.disabled=true;button.textContent="Verifying…";try{const actual=await hashInBrowser(active);if(actual===expected){state.className="integrity good";state.innerHTML="<i></i><span>sha256 verified in this browser · unsigned</span>";button.textContent="Verified ✓";}else{state.className="integrity bad";state.innerHTML="<i></i><span>sha256 mismatch</span>";button.textContent="Hash mismatch";}}catch(error){state.className="integrity bad";state.innerHTML="<i></i><span>Web Crypto unavailable · use receipts verify</span>";button.textContent="Verification unavailable";}button.disabled=false;},{once:true});
  $("load-receipt").addEventListener("click",()=>$("manifest-file").click()); $("manifest-file").addEventListener("change",async(event)=>{const file=event.target.files?.[0];if(!file)return;try{mount(JSON.parse(await file.text()));$("integrity").className="integrity";$("integrity").innerHTML="<i></i><span>loaded locally · ready to verify</span>";}catch(error){alert("That file is not valid Receipts manifest JSON.");}event.target.value="";});
  $("download-receipt").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(active,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`receipts-${active.meta?.session_id||"session"}.json`;link.click();URL.revokeObjectURL(url);});
  $("copy-link").addEventListener("click",async()=>{const button=$("copy-link"),url=`${location.href.split("#")[0]}#${selectedId||"evidence"}`;try{await navigator.clipboard.writeText(url);button.textContent="Link copied ✓";}catch(error){button.textContent="Copy unavailable";}setTimeout(()=>{button.textContent="Copy share link";},1800);});
  mount(initialManifest);
})();
</script>
</body>
</html>'''


def render_replay(manifest: dict[str, Any]) -> str:
    """Render an offline, single-file interactive replay with its manifest embedded."""
    embedded = json.dumps(manifest, ensure_ascii=False).replace("</", "<\\/")
    return _TEMPLATE.replace("__MANIFEST_JSON__", embedded)


def write_replay(manifest: dict[str, Any], output: Path, open_browser: bool = True) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_replay(manifest), encoding="utf-8")
    if open_browser:
        try:
            webbrowser.open(output.resolve().as_uri())
        except OSError:
            pass
    return output
